config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'bonjour(/:name)', to: 'pages#salut', as: 'salut'
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def salut
    @name = params[:name]
  end

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path

  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rorformation</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="<%= root_path %>">Rubyonrails</a>



        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link" href="<%= salut_path %>">Salut</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= posts_path %>">Posts</a>
          </li>


        </ul>


    </nav>

    <div class="container">

    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
Bienvenue sur le site

app/views/pages/salut.html.erb
Salut <%= @name %> comment ça va ?

app/views/posts/edit.html.erb
<h1>Editer l'article</h1>

<%= form_for @post do |f| %>

    <div class="form-group">

      <label>Titre de l'article</label>
      <%= f.text_field :title, class: 'form-control' %>

    </div>
    <div class="form-group">

      <label>Contenu</label>
      <%= f.text_area :content, class: 'form-control' %>

    </div>
    <div class="form-group">

      <button type="submit" class="btn btn-primary">Modifier l'article</button>

    </div>

<% end %>

app/views/posts/index.html.erb
<h1>Articles du blog</h1>

<p>
  <a href="<%= new_post_path %>" class="btn btn-success">Créer l'article</a>
</p>
<%= @posts.each do |post| %>
    <h2><%= post.title %></h2>
    <p> <%= post.content %></p>
    <p>
      <a href="<%= post_path(post.id) %>" class="btn btn-primary">Lire la suite</a>
      <a href="<%= edit_post_path(post.id) %>" class="btn btn-primary">Editer</a>
      <a href="<%= post_path(post.id) %>" class="btn btn-danger" data-confirm=""Etes vous sur?" data-method="DELETE">Supprimer</a>
    </p>
    <% end %>

app/views/posts/new.html.erb
<h1>Créer un article</h1>

<%= form_for @post do |f| %>

    <div class="form-group">

      <label>Titre de l'article</label>
      <%= f.text_field :title, class: 'form-control' %>

    </div>
    <div class="form-group">

      <label>Contenu</label>
      <%= f.text_area :content, class: 'form-control' %>

    </div>
    <div class="form-group">

      <button type="submit" class="btn btn-primary">Créer l'article</button>

    </div>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<p>
  <a href="<%= posts_path %>" class="btn btn-primary">
    Retour aux articles
  </a>
</p>